version: "3.8"

services:
  studio-gateway:
    image: node:20-alpine
    container_name: ov-studio-gateway
    working_dir: /app
    command: ["node", "server.js"]
    ports:
      - "3001:3001"
    environment:
      - OPENVOICE_BASE_URL=http://10.0.0.235:8786
      - REF_DIR=/refs
      - OUT_DIR=/outs
    volumes:
      - ./gateway:/app:ro
      - /mnt/user/appdata/openvoice/ref:/refs:ro
      - /mnt/user/appdata/openvoice/audio_out:/outs:ro
    networks: [studio]
    restart: unless-stopped

  studio-frontend:
    image: node:20-alpine
    container_name: ov-studio-frontend
    working_dir: /app
    command: ["sh", "-lc", "npm ci && npm run build && npx http-server dist -p 8099 --silent"]
    ports:
      - "8099:8099"
    volumes:
      - ./frontend:/app:ro
    depends_on:
      - studio-gateway
    networks: [studio]
    restart: unless-stopped

networks:
  studio: {}
